const cfg=window.MUSHRA_CONFIG||{}, state={participant:'',trials:[],order:[],current:0,answers:{},startedAt:null};let currentAudio=null,currentButton=null;
const $=s=>document.querySelector(s), screens=['welcome','test','done'];
function show(id){screens.forEach(x=>$('#'+x).classList.toggle('active',x===id))}
function hash(s){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){return()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/4294967296)}
function shuffle(a,seed){let r=rng(seed),x=[...a];for(let i=x.length-1;i;i--){let j=Math.floor(r()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function save(){localStorage.setItem('thinksep_mushra_progress',JSON.stringify({participant:state.participant,order:state.order,current:state.current,answers:state.answers,startedAt:state.startedAt}))}
function stopAll(except=null){document.querySelectorAll('audio').forEach(a=>{if(a!==except)a.pause()});if(currentAudio&&currentAudio!==except)currentAudio.pause();if(currentButton&&currentAudio!==except)currentButton.textContent='▶ Play sample';if(currentAudio!==except){currentAudio=null;currentButton=null}}
function start(){let id=$('#participant').value.trim();if(!id||!$('#consent').checked){$('#startError').textContent='Enter a participant ID and confirm consent.';return}let old;try{old=JSON.parse(localStorage.getItem('thinksep_mushra_progress'))}catch(e){}if(old&&old.participant===id&&old.order?.length===state.trials.length){Object.assign(state,old)}else{state.participant=id;state.startedAt=new Date().toISOString();state.order=shuffle(state.trials.map((_,i)=>i),hash(id+'trials'));state.current=0;state.answers={}}save();show('test');render()}
function render(){stopAll();let trial=state.trials[state.order[state.current]],key=trial.id,ans=state.answers[key]||{scores:{},played:{},changed:{},started:Date.now()};state.answers[key]=ans;$('#progressText').textContent=`TRIAL ${state.current+1} / ${state.trials.length}`;$('#trialMeta').textContent=`${trial.task.toUpperCase()} · ${trial.attribute}`;$('#instruction').textContent=trial.instruction;$('#mixture').src=trial.mixture;$('#reference').src=trial.reference;['mixture','reference'].forEach(k=>{$('#'+k).onplay=()=>{stopAll($('#'+k));ans.played[k]=true;save()}});let candidates=[...Object.entries(trial.systems).map(([identity,src])=>({identity,src})),{identity:'hidden_reference',src:trial.reference},{identity:'anchor',src:trial.anchor}];candidates=shuffle(candidates,hash(state.participant+key));let box=$('#systems');box.innerHTML='';candidates.forEach((c,i)=>{let code=String.fromCharCode(65+i),f=$('#systemTemplate').content.cloneNode(true),article=f.querySelector('.system'),audio=new Audio(c.src),play=f.querySelector('.play'),slider=f.querySelector('.slider'),score=f.querySelector('.score');f.querySelector('.system-name').textContent=`SYSTEM ${code}`;slider.value=ans.scores[c.identity]??50;score.textContent=slider.value;if(ans.played[c.identity])play.classList.add('played');play.onclick=()=>{if(currentAudio===audio&&!audio.paused){audio.pause();play.textContent='▶ Resume';return}stopAll();currentAudio=audio;currentButton=play;audio.play();play.textContent='❚❚ Pause';play.classList.add('played');ans.played[c.identity]=true;save()};audio.onended=()=>{play.textContent='↻ Play again';currentAudio=null;currentButton=null;audio.currentTime=0};slider.oninput=()=>{score.textContent=slider.value;ans.scores[c.identity]=Number(slider.value);ans.changed[c.identity]=true;save()};article.dataset.identity=c.identity;box.append(f)});$('#previous').disabled=state.current===0;$('#trialError').textContent='';save()}
function validate(){let t=state.trials[state.order[state.current]],a=state.answers[t.id],ids=[...Object.keys(t.systems),'hidden_reference','anchor'];if(!a.played.mixture||!a.played.reference||ids.some(x=>!a.played[x]))return 'Please listen to the mixture, reference, and every system.';if(ids.some(x=>!a.changed[x]))return 'Please actively set a score for every system.';a.completedAt=Date.now();return ''}
async function next(){let e=validate();if(e){$('#trialError').textContent=e;return}save();await submitSnapshot('partial');if(state.current===state.trials.length-1){show('done');$('#progressText').textContent='COMPLETE'}else{state.current++;save();render();scrollTo(0,0)}}
function previous(){if(state.current){state.current--;render();scrollTo(0,0)}}
function payload(type){return{recordType:type,studyId:cfg.studyId,participantId:state.participant,startedAt:state.startedAt,savedAt:new Date().toISOString(),userAgent:navigator.userAgent,completedTrials:Object.values(state.answers).filter(x=>x.completedAt).length,currentTrial:state.current+1,trialOrder:state.order.map(i=>state.trials[i].id),responses:state.answers}}
async function submitSnapshot(type='partial'){if(!cfg.submitEndpoint||!state.participant)return false;let body=payload(type);try{let r=await fetch(cfg.submitEndpoint,{method:'POST',keepalive:true,headers:{'Content-Type':'application/json','apikey':cfg.publishableKey,'Authorization':`Bearer ${cfg.publishableKey}`,'Prefer':'return=minimal'},body:JSON.stringify({study_id:cfg.studyId,participant_id:state.participant,payload:body})});return r.ok}catch(e){return false}}
async function submit(){let button=$('#submit'),out=$('#submitState');button.disabled=true;out.textContent='Submitting…';if(await submitSnapshot('final')){localStorage.removeItem('thinksep_mushra_progress');out.textContent='Submitted successfully. You may close this page.';button.textContent='Submitted ✓'}else{out.textContent='Submission failed. Your progress remains saved; please try again.';button.disabled=false}}
fetch('trials.json?v=2').then(r=>r.json()).then(d=>{state.trials=d;$('#start').onclick=start;$('#next').onclick=next;$('#previous').onclick=previous;$('#saveExit').onclick=async()=>{save();await submitSnapshot('partial');show('welcome');$('#progressText').textContent='SAVED'};$('#submit').onclick=submit});
